services:
  db:
    container_name: 'book-store-db'
    image: postgres:17-alpine3.20
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: postgres

  cache:
    image: redis:7-alpine3.20
    container_name: 'book-store-redis'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  app:
    container_name: 'book-store-app'
    image: minhnghia2k3/book-store-app:latest
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changemeinprod!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
      - cache

volumes:
  postgres:
  cache: